Running on d-9-14-2
Python location: /home/gridsan/brich/.conda/envs/gte_large_en_v1-5/bin/python
Python version: Python 3.10.16
Torch location: /home/gridsan/brich/.conda/envs/gte_large_en_v1-5/lib/python3.10/site-packages/torch/__init__.py
Loading train set from data_files/datasets/rmanluo_RoG-cwq_train.json
Loading validation set from data_files/datasets/rmanluo_RoG-cwq_validation.json
Loading test set from data_files/datasets/rmanluo_RoG-cwq_test.json
# raw samples: 27639 | # processed samples: 22089
# raw samples: 3519 | # processed samples: 2848
# raw samples: 3531 | # processed samples: 3531
Using cache directory: /home/gridsan/brich/subgraphrag/BenSubgraphRag/SubGraphRag/retrieve/model_cache
Attempting to load model from local cache: /home/gridsan/brich/subgraphrag/BenSubgraphRag/SubGraphRag/retrieve/model_cache
done
